ДЗ Дебаг
NikolayARV/homeWork17 pull request #7
Opened 2023-01-31 19:19 UTC by NikolayARV

ДЗ добавление эндпоинта для вывода всех рецептов

2023-02-01 18:40 UTC, alekseykoshelev requested changes

2023-02-01 18:40 UTC, alekseykoshelev commented on src/main/java/com/example/recipeapp/model/Ingredients.java
> +    public String toString() {
А у тебя ведь стоит уже аннотация @ToString от lombok.

2023-02-01 18:40 UTC, alekseykoshelev commented on src/main/java/com/example/recipeapp/model/Ingredients.java
> +
Также геттеры можешь сделать через lombok

2023-02-01 18:40 UTC, alekseykoshelev commented on src/main/java/com/example/recipeapp/controllers/RecipeController.java
> +   public ResponseEntity<Void> getAllRecipes() {
Странный метод, он же ничего не возвращает.

2023-02-02 18:50 UTC, NikolayARV commented on src/main/java/com/example/recipeapp/model/Ingredients.java
> +    public String toString() {
Лишнюю аннотацию убрал. toString переопределил сам, т.к. мне не нравятся лишние символы при переопределении toString от lombok.

2023-02-02 18:50 UTC, NikolayARV commented on src/main/java/com/example/recipeapp/model/Ingredients.java
> +
Да, геттеры сделал через lombok

2023-02-02 18:50 UTC, NikolayARV commented on src/main/java/com/example/recipeapp/controllers/RecipeController.java
> +   public ResponseEntity<Void> getAllRecipes() {
Да, странный. Это я не подчистил результат эксперимента.

2023-02-11 17:58 UTC, merged